### PR TITLE
#154953777 Fix failing Travis

### PR DESCRIPTION
**Pull request by Sylvance**
### What does this PR do?
This PR fixes failing travis

### Description of Task to be completed?
Integrate travis with slack

### How should this be manually tested?
When you push to this repo, then travis runs automatically

### Any background context you want to provide?
Removed versions of python not needed.

### What are the relevant pivotal tracker stories?
[https://www.pivotaltracker.com/story/show/154953777](154953777)

### CODE REVIEW

**Review by JoyyToo — APPROVED** [review]
LGTM

**Comment by muchai-mercy** [comment]
@Sylvance squash commits and solve for linting on `travis.yml`

**Comment by muchai-mercy** [comment]
Please add to the `.gitignore` the `.DS_Store`

**Review by muchai-mercy — APPROVED** [review]
LGTM

**Comment by shakirandagire** [comment]
This looks good. Amazing work Sylvance

**Comment by nyandiekaFelix** [comment]
LGTM

**Review by kevinsamoei — APPROVED** [review]
Well done @Sylvance.

**Review by nyandiekaFelix — APPROVED** [review]

**Pull request merged**
