### PR TITLE
#155322966 Fix social login bug

### PR DESCRIPTION
**Pull request by kevinsamoei**
#### What does this PR do?
Fix a bug that is causing the social login i.e with Twitter, Facebook, and Google not to work. It also updates the requirements_devel file which causes errors during runtime.
#### Description of Task to be completed?
The current develop branch settings module has two AUTHENTICATION_BACKENDS. For the social login,s to work, we need to remove one. 
#### How should this be manually tested?
On the login page, when one tries to login with either Twitter, Facebook or Google, the application should be able to log the user in.
#### What are the relevant pivotal tracker stories?
[155322966](https://www.pivotaltracker.com/story/show/155322966)
#### Screenshots (if appropriate)
* With the bug in place
screen shot 2018-02-19 at 12 41 37
* With the bug fixed
screen shot 2018-02-19 at 12 42 52

### CODE REVIEW

**Review by JoyyToo — APPROVED** [review]
LGTM

**Review by hadijahkyampeire — APPROVED** [review]
LGTM

**Review by shakirandagire — COMMENTED** [review]
This looks good

**Review by muchai-mercy — APPROVED** [review]
LGTM

**Pull request merged**
