### PR TITLE
 #154953796 Rework landing page

### PR DESCRIPTION
**Pull request by Sylvance**
#### What does this PR do?
Reworks the landing page.

#### Description of Task to be completed?
User needs to be able to understand all features of the product on the landing page before scrolling.

#### How should this be manually tested?
On landing on the Wger app user should be able to see all the details before scrolling.

#### Any background context you want to provide?
The landing page was consisting of texts only before this rework.

#### What are the relevant pivotal tracker stories?
[#154953796](https://www.pivotaltracker.com/story/show/154953796)

#### Screenshots (if appropriate)
screen shot 2018-02-26 at 17 15 06
screen shot 2018-02-26 at 17 15 24
screen shot 2018-02-26 at 17 15 35
screen shot 2018-02-26 at 17 16 02
screen shot 2018-02-26 at 17 16 15

#### Questions:

### CODE REVIEW

**Comment by Sylvance** [comment]
@Mercy-Muchai I have made the appropriate changes, take a look.

**Comment by muchai-mercy** [comment]
@Sylvance we shall review this more after your sync with the PO. For now it will remain open.

**Review by muchai-mercy — CHANGES_REQUESTED** [review]
Remove some of the images that aren't in use anymore

**Review by muchai-mercy — APPROVED** [review]
LGTM

**Pull request merged**
